var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/instances/[instanceId]/terminal/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0guj327._.js")
R.c("server/chunks/ssr/_00658nu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0_p4.yr.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l9lo_1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__002agwm._.js")
R.c("server/chunks/ssr/[root-of-the-server]__11ip~lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/0zjb_server_app_dashboard_instances_[instanceId]_terminal_page_actions_0ggcg-s.js")
R.m(33408)
module.exports=R.m(33408).exports
